**4. TO - DO - Task**

**4.1 Exercises on Functions**

 Task 1



In [1]:
def meters_to_feet(meters):
    """
    Convert meters to feet.
    :param meters: Value in meters (float)
    :return: Equivalent value in feet (float)
    """
    return meters * 3.28084

def feet_to_meters(feet):
    """
    Convert feet to meters.
    :param feet: Value in feet (float)
    :return: Equivalent value in meters (float)
    """
    return feet / 3.28084

def kilograms_to_pounds(kg):
    """
    Convert kilograms to pounds.
    :param kg: Value in kilograms (float)
    :return: Equivalent value in pounds (float)
    """
    return kg * 2.20462

def pounds_to_kilograms(lbs):
    """
    Convert pounds to kilograms.
    :param lbs: Value in pounds (float)
    :return: Equivalent value in kilograms (float)
    """
    return lbs / 2.20462

def liters_to_gallons(liters):
    """
    Convert liters to gallons.
    :param liters: Value in liters (float)
    :return: Equivalent value in gallons (float)
    """
    return liters * 0.264172

def gallons_to_liters(gallons):
    """
    Convert gallons to liters.
    :param gallons: Value in gallons (float)
    :return: Equivalent value in liters (float)
    """
    return gallons / 0.264172

def main():
    print("Unit Converter")
    print("1. Length (meters to feet, feet to meters)")
    print("2. Weight (kilograms to pounds, pounds to kilograms)")
    print("3. Volume (liters to gallons, gallons to liters)")

    try:
        choice = int(input("Choose a conversion type (1-3): "))
        if choice == 1:
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = int(input("Choose conversion (1-2): "))
            if sub_choice == 1:
                value = float(input("Enter meters: "))
                print(f"{value} meters = {meters_to_feet(value):.2f} feet")
            elif sub_choice == 2:
                value = float(input("Enter feet: "))
                print(f"{value} feet = {feet_to_meters(value):.2f} meters")
            else:
                print("Invalid choice.")
        elif choice == 2:
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = int(input("Choose conversion (1-2): "))
            if sub_choice == 1:
                value = float(input("Enter kilograms: "))
                print(f"{value} kg = {kilograms_to_pounds(value):.2f} lbs")
            elif sub_choice == 2:
                value = float(input("Enter pounds: "))
                print(f"{value} lbs = {pounds_to_kilograms(value):.2f} kg")
            else:
                print("Invalid choice.")
        elif choice == 3:
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = int(input("Choose conversion (1-2): "))
            if sub_choice == 1:
                value = float(input("Enter liters: "))
                print(f"{value} L = {liters_to_gallons(value):.2f} gal")
            elif sub_choice == 2:
                value = float(input("Enter gallons: "))
                print(f"{value} gal = {gallons_to_liters(value):.2f} L")
            else:
                print("Invalid choice.")
        else:
            print("Invalid choice. Please select a valid option.")
    except ValueError:
        print("Invalid input. Please enter a numeric value.")

if __name__ == "__main__":
    main()

Unit Converter
1. Length (meters to feet, feet to meters)
2. Weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)
Choose a conversion type (1-3): 3
1. Liters to Gallons
2. Gallons to Liters
Choose conversion (1-2): 1
Enter liters: 2
2.0 L = 0.53 gal


Tasks 2

In [2]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    :param numbers: List of numerical values.
    :return: Sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    :param numbers: List of numerical values.
    :return: Average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Find the maximum value in a list of numbers.

    :param numbers: List of numerical values.
    :return: Maximum value in the list.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Find the minimum value in a list of numbers.

    :param numbers: List of numerical values.
    :return: Minimum value in the list.
    """
    return min(numbers)

def main():
    print("Mathematical Operations on a List")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Choose an operation (1-4): "))
        numbers = input("Enter a list of numbers separated by spaces: ").split()

        # Convert input to a list of floats
        numbers = [float(num) for num in numbers]

        if not numbers:
            raise ValueError("The list is empty. Please enter some numbers.")

        if choice == 1:
            print(f"Sum: {calculate_sum(numbers)}")
        elif choice == 2:
            print(f"Average: {calculate_average(numbers):.2f}")
        elif choice == 3:
            print(f"Maximum: {find_maximum(numbers)}")
        elif choice == 4:
            print(f"Minimum: {find_minimum(numbers)}")
        else:
            print("Invalid choice. Please select a valid option.")

    except ValueError as e:
        print(f"Error: {e}. Please enter valid numerical values.")

if __name__ == "__main__":
    main()

Mathematical Operations on a List
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 3
Enter a list of numbers separated by spaces: 4
Maximum: 4.0


**4.2 Exercise on List Manipulation**

1. Extract Every Other Element

In [3]:
def extract_every_other(lst):
    """
    Extract every other element from a list, starting from the first element.

    :param lst: List of elements.
    :return: A new list containing every other element.
    """
    return lst[::2]  # Using list slicing to get every second element

num_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(num_list)
print(result)

[1, 3, 5]


2. Slice a Sublist

In [4]:
def get_sublist(lst, start, end):
  """
  Returns a sublist from the given list, starting from 'start' index and ending at 'end' index (inclusive).

  :param lst: List from which sublist is to be extracted
  :param start: Starting index of the sublist
  :param end: Ending index of the sublist (inclusive)
  :return: Sublist from start to end index (inclusive)
  """
  return lst[start:end+1]

start = 2
end = 4
lst = [1,2,3,4,5,6]
print("Output: ",get_sublist(lst, start, end))

Output:  [3, 4, 5]


3. Reverse a List Using Slicing

In [5]:
def reverse_list(lst):
  """
  Returns a reversed list using slicing.

  :param lst: List to be reversed
  :return: Reversed list
  """

  return lst[::-1]

lst = [1,2,3,4,5,6,7,8,9]
print("Reverse list: ",reverse_list(lst))

Reverse list:  [9, 8, 7, 6, 5, 4, 3, 2, 1]


4. Remove the First and Last Elements

In [6]:
def remove_first_last(lst):
  """
  Removes the first and last elements of a list and returns the resulting sublist.

  :param lst: List from which first and last elements should be removed
  :return: Sublist without the first and last elements
  """
  return lst[1:-1]

list = [1,2,5,2,3,6,1]
print("Sublist: ",remove_first_last(list))

Sublist:  [2, 5, 2, 3, 6]


5. Get the First n Elements

In [7]:
def get_first_n(lst, n):
  """
  Returns the first n elements from a given list using slicing.

  :param lst: List from which elements are to be extracted
  :param n: Number of elements to extract from the beginning
  :return: List containing the first n elements
  """
  return lst[:n]

num = 4
list = [3,2,5,8,9,1,2]
print("First nth elements: ", get_first_n(list,num))


First nth elements:  [3, 2, 5, 8]


6. Extract Elements from the End

In [8]:
def get_last_n(lst, n):
  """
  Returns the last n elements from a given list using slicing.

  :param lst: List from which elements are to be extracted
  :param n: Number of elements to extract from the end
  :return: List containing the last n elements
  """
  return lst[-n:] if n > 0 else []

num = 2
list = [3,2,5,8,9,1,2]
print("First nth elements: ", get_last_n(list,num))

First nth elements:  [1, 2]


7. Extract Elements in Reverse Order

In [9]:
def reverse_skip(lst):
  """
  Returns a list of elements in reverse order, starting from the second-to-last element
  and skipping one element in between.

  :param lst: List from which elements are to be extracted
  :return: New list containing every second element in reverse order
  """

  return lst[-2::-2]

list = [2,1,3,6,7,9]

print("New list: ",reverse_skip(list))

New list:  [7, 3, 2]


**4.3 Exercise on Nested List**
1. Flatten a Nested List

In [10]:
def flatten(lst):
  flat_list = []
  for row in lst:
    flat_list.extend(row)
  return flat_list


list = [[1,2,3],[6,7,8],[3,2,1]]
print("Flatten list: ",flatten(list))

Flatten list:  [1, 2, 3, 6, 7, 8, 3, 2, 1]


2. Accessing Nested List Elements

In [11]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element


nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print("Nested List Elements: ",access_nested_element(nested_list, indices))

Nested List Elements:  6


3. Sum of All Elements in a Nested List

In [12]:
def sum_nested(lst):
    # List comprehension answer ->
    # return [item for sublist in lst for item in sublist]
    res = []
    for i in lst:
        for j in i:
            res.append(j)

    return sum(res)

res = sum_nested([[1, 2], [3, 4], [5]])
print("Sum of Elements: ",res)

Sum of Elements:  15


4. Remove Specific Element from a Nested List

In [13]:
def remove_element(lst, elem):
    for i in lst:
        if elem in i:
            i.remove(elem)

    return lst

res = remove_element([[1, 2], [3, 4], [2,5]], 2)
print("New list: ",res)

New list:  [[1], [3, 4], [5]]


5. Find the Maximum Element in a Nested List

In [14]:
def flatten_list(lst):
    # convert it to string, strip unnecessary characters
    tmp = str(lst)
    tmp = tmp.strip("[]")
    tmp = tmp.replace("[", "").replace("]", "").replace(" ", "")
    t_arr = tmp.split(",")

    return [int(i) for i in t_arr]


def find_max(lst):
    return max(flatten_list(lst))

print("Maximum Element in a Nested List: ",find_max([[1, 2], [3, [4, 5]], 6]))

Maximum Element in a Nested List:  6


6. Count Occurrences of an Element in a Nested List

In [15]:
def count_occurrences(lst, elem):
    """
    Counts the occurrences of an element in a nested list.

    Args:
        lst: The nested list to search.
        elem: The element to count.

    Returns:
        The number of times the element appears in the list.
    """
    count = 0
    for sublist in lst:
        for item in sublist:
            if item == elem:
                count += 1
    return count
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print("Occurrences Count: ",count_occurrences(lst, elem))

Occurrences Count:  3


7. Flatten a List of Lists of Lists

In [16]:
def deep_flatten(lst):
    # convert it to string, strip unnecessary characters
    tmp = str(lst)
    tmp = tmp.strip("[]")
    tmp = tmp.replace("[", "").replace("]", "").replace(" ", "")
    t_arr = tmp.split(",")

    return [int(i) for i in t_arr]

print("List: ",deep_flatten([[1, 2], [3, [4, 5]], 6]))

List:  [1, 2, 3, 4, 5, 6]


8. Nested List Average

In [17]:
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.

    Args:
        lst: A nested list of numbers.

    Returns:
        The average of all elements in the nested list.
        Returns 0 if the list is empty or contains no numbers.
    """
    total = 0
    count = 0
    for sublist in lst:
        for num in sublist:
            try:
                total += num
                count += 1
            except TypeError:
                # Handle cases where a sublist element isn't a number
                print(f"Warning: Non-numeric element '{num}' encountered. Skipping.")
                continue
    return total / count if count > 0 else 0

list = [[1, 2], [3, 4], [5, 6]]
print("The average: ",average_nested(list))

The average:  3.5


**10. To - Do - NumPy**

**10.1 Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:

In [18]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), 7)  # Example: 3x3 array filled with 7
print("\nArray Filled with 7 (3x3):\n", fill_value_array)

# 4. Return a new array of zeros with same shape and type as a given array
sample_array = np.array([[5, 10, 15], [20, 25, 30]])
zeros_like_array = np.zeros_like(sample_array)
print("\nZeros Array with Same Shape as Sample Array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(sample_array)
print("\nOnes Array with Same Shape as Sample Array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)

Empty Array (2x2):
 [[1.59136064e-316 0.00000000e+000]
 [2.29847904e+291 1.38216227e-075]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Sample Array:
 [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as Sample Array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

In [19]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array with values from 10 to 49:\n", arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", arr2)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_arr = np.random.random(30)
mean_value = random_arr.mean()
print("\nRandom Array (size 30):\n", random_arr)
print("Mean of the Random Array:", mean_value)

# 5. Create a 10x10 array with random values and find min/max
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\n10x10 Random Matrix:\n", random_matrix)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th Element as 1:\n", zero_array)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array (size 30):
 [0.9273679  0.89955482 0.4421856  0.98783919 0.12833464 0.39406352
 0.36681988 0.73430745 0.49380408 0.55323488 0.98176013 0.93521885
 0.13757327 0.6068766  0.33157693 0.85892851 0.07850749 0.39627729
 0.65587025 0.96924409 0.2072562  0.45410453 0.39535254 0.46320263
 0.40098191 0.69800868 0.37554076 0.57143627 0.5671236  0.0626341 ]
Mean of the Random Array: 0.5358328866880154

10x10 Random Matrix:
 [[0.29584614 0.90862683 0.83895435 0.43468451 0.65614419 0.72824755
  0.57220787 0.9167786  0.71073448 0.18998678]
 [0.6290464  0.87215933 0.86637387 0.87474311 0.83143853 0.99352056
  0.55690501 0.89261183 0.10215739 0.28517799]
 [0.91462042 0.36168235 0.64689661 0.14118867 0.17771426 

Problem - 3: Array Operations

In [20]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays (x + y)
add_result = x + y
print("1. Addition of x and y:\n", add_result)

# 2. Subtract the two arrays (x - y)
subtract_result = x - y
print("\n2. Subtraction of x and y:\n", subtract_result)

# 3. Multiply the array with any integer of your choice (e.g., multiply x by 2)
multiply_result = x * 2
print("\n3. Multiply x by 2:\n", multiply_result)

# 4. Find the square of each element of the array (x ** 2)
square_result = x ** 2
print("\n4. Square of each element of x:\n", square_result)

# 5. Find the dot product between:
# v and w
dot_vw = np.dot(v, w)
print("\n5. Dot product between v and w:", dot_vw)

# x and v
dot_xv = np.dot(x, v)
print("\nDot product between x and v:\n", dot_xv)

# x and y
dot_xy = np.dot(x, y)
print("\nDot product between x and y:\n", dot_xy)

# 6. Concatenate x and y along row and v and w along column

# Concatenate x and y along rows (axis=0)
concat_xy_row = np.concatenate((x, y), axis=0)
print("\n6. Concatenate x and y along row:\n", concat_xy_row)

# Concatenate v and w along columns (axis=1)
v_w_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenate v and w along column:\n", v_w_column)

# 7. Concatenate x and v; if you get an error, observe and explain why

try:
    concat_xv = np.concatenate((x, v), axis=1)
    print("\n7. Concatenate x and v along columns:\n", concat_xv)
except ValueError as e:
    print("\nError:", e)

1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiply x by 2:
 [[ 2  4]
 [ 6 10]]

4. Square of each element of x:
 [[ 1  4]
 [ 9 25]]

5. Dot product between v and w: 219

Dot product between x and v:
 [29 77]

Dot product between x and y:
 [[19 22]
 [50 58]]

6. Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along column:
 [[ 9 11]
 [10 12]]

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations

In [21]:
import numpy as np

# Given arrays A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A * A^(-1) = I (Identity Matrix)
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("1. A * A^(-1) = Identity Matrix:\n", identity_matrix)

# Task 2: Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB != BA:")
print("AB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

# Task 3: Prove (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)  # (AB)^T
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))  # B^T * A^T
print("\n3. (AB)^T = B^T * A^T:")
print("(AB)^T:\n", AB_transpose)
print("B^T * A^T:\n", B_transpose_A_transpose)
print("Are (AB)^T and B^T * A^T equal?", np.array_equal(AB_transpose, B_transpose_A_transpose))

# Task 4: Solve the system of linear equations using Inverse Method
# Represent the system in matrix form A * X = B
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_system = np.array([-1, -3, 9])

# Using the Inverse of A to solve for X
A_inv_system = np.linalg.inv(A_system)
X = np.dot(A_inv_system, B_system)
print("\n4. Solution of the system of linear equations (using Inverse method):")
print(f"x = {X[0]}, y = {X[1]}, z = {X[2]}")

# Task 5: Solve the system using np.linalg.solve function
# This is another approach using np.linalg.solve
X_solve = np.linalg.solve(A_system, B_system)
print("\n5. Solution of the system using np.linalg.solve:")
print(f"x = {X_solve[0]}, y = {X_solve[1]}, z = {X_solve[2]}")

1. A * A^(-1) = Identity Matrix:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB != BA:
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA equal? False

3. (AB)^T = B^T * A^T:
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal? True

4. Solution of the system of linear equations (using Inverse method):
x = 2.0, y = 1.0, z = -2.0

5. Solution of the system using np.linalg.solve:
x = 2.0, y = 1.0000000000000002, z = -2.0


**10.2 Experiment: How Fast is Numpy?**

1. Element-wise Addition

In [22]:
import time
import numpy as np

# List size
size = 1_000_000

# Generate two Python lists with random values
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Measure time for Python list addition
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken using Python lists: {python_time:.6f} seconds")

# Generate two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Measure time for NumPy array addition
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken using NumPy arrays: {numpy_time:.6f} seconds")

# Performance comparison
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists.")

Time taken using Python lists: 0.114903 seconds
Time taken using NumPy arrays: 0.005260 seconds
NumPy is approximately 21.84 times faster than Python lists.


2. Element-wise Multiplication

In [23]:
import time
import numpy as np

# List size
size = 1_000_000

# Generate two Python lists with values from 0 to size-1
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Measure time for Python list multiplication
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken using Python lists: {python_time:.6f} seconds")

# Generate two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Measure time for NumPy array multiplication
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken using NumPy arrays: {numpy_time:.6f} seconds")

# Performance comparison
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists.")

Time taken using Python lists: 0.127190 seconds
Time taken using NumPy arrays: 0.005450 seconds
NumPy is approximately 23.34 times faster than Python lists.


3. Dot Product

In [24]:
import time
import numpy as np

# List size
size = 1_000_000

# Generate two Python lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Measure time for dot product using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken using Python lists: {python_time:.6f} seconds")

# Generate two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Measure time for dot product using NumPy arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken using NumPy arrays: {numpy_time:.6f} seconds")

# Performance comparison
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists.")

Time taken using Python lists: 0.202785 seconds
Time taken using NumPy arrays: 0.002050 seconds
NumPy is approximately 98.90 times faster than Python lists.


4. Matrix Multiplication

In [25]:
import time
import numpy as np

# Matrix size
size = 1000

# Generate two matrices using Python lists
matrix1 = [[i * j for j in range(size)] for i in range(size)]
matrix2 = [[j * i for j in range(size)] for i in range(size)]

# Measure time for matrix multiplication using Python lists
start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken using Python lists: {python_time:.6f} seconds")

# Generate two NumPy matrices
array1 = np.array(matrix1)
array2 = np.array(matrix2)

# Measure time for matrix multiplication using NumPy
start_time = time.time()
result_array = np.dot(array1, array2)  # or array1 @ array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken using NumPy arrays: {numpy_time:.6f} seconds")

# Performance comparison
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists.")

Time taken using Python lists: 180.814936 seconds
Time taken using NumPy arrays: 2.288671 seconds
NumPy is approximately 79.00 times faster than Python lists.
